# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UCSB_Amenities' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UCSB_Amenities
  pod 'Parse'
  pod 'AlamofireImage'

  target 'UCSB_AmenitiesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'UCSB_AmenitiesUITests' do
    # Pods for testing
  end

end
